platforms:
  android:
    versionName: 3.10.6
    versionCode: 310600
    manifest:
      - file: AndroidManifest.xml
        target: manifest/application
        inject: <service android:name="com.equimaps.capacitor_background_geolocation.BackgroundGeolocationService" android:enabled="true" android:exported="true" android:foregroundServiceType="location" />

      - file: AndroidManifest.xml
        target: /manifest
        merge: |
          <manifest>
            <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
            <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
            <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
            <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />
            <uses-feature android:name="android.hardware.location.gps" />
            <queries>
              <package android:name="com.google.android.apps.maps" />
            </queries>
          </manifest>
  ios:
    targets:
      App:
        version: 3.10.6
        buildNumber: 310600
        plist:
          - replace: true
            entries:
              - NSLocationWhenInUseUsageDescription: In order to track you while hiking, this app requires location tracking

          - replace: true
            entries:
              - NSLocationAlwaysAndWhenInUseUsageDescription: In order to track you while hiking, this app always requires location tracking

          - replace: true
            entries:
              - UIBackgroundModes:
                  - location
